### PR TITLE
added check for escaped file paths

### LINKED ISSUE #21: when a folder has a + in the name, the server cannot find content in it
looks like there is some issue with escaping folder names or something like that.

when the server comes across a folder that has a `+` sign, the contents are returned as `404`. it's browseable, however.

we have a hole in our testing, looks like we tested file names but not folder names?

### PR DESCRIPTION
**Pull request by vishwasmittal**
Fixes #21

### CODE REVIEW

**Comment by vishwasmittal** [comment]
@cpg it will check for file names containing the escape characters as well. So, if the request is something like: `/files?s=shareName;p=path+name`, it will check for file/folder named `path+name` if found, return it else will check for `path name` and follow the standard procedure.

**Comment by cpg** [comment]
Ugh, actually, this does not appear to work for a folder named like this: `A + B`

**Comment by vishwasmittal** [comment]
@cpg yeah, you are right it does fail these cases. I can see an easy way out but it depends on whether you want it just for the `+` symbol or for other symbols as well (if yes then specify the other symbols too).

**Comment by cpg** [comment]
I should point out that the failure at the moment appears to be due to the space. `A+B` works, however, `A + B` fails. Space was not a problem before.

**Pull request merged**
